board/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('profile/', include("profiles.urls")),
    path("accounts/", include("allauth.urls")),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path("accounts/", include("accounts.urls")),
    path('', include("config.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/models.py
from django.urls import reverse

from django.contrib.auth.models import User
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.core.cache import cache


class Category(MPTTModel):
    name = models.CharField('Имя', max_length=50, unique=True)
    """Категории объявлений"""
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',
        verbose_name="Родитель"
    )
    slug = models.SlugField('url', max_length=50, unique=True)

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']
        verbose_name = "Категория"




class FilterAdvert(models.Model):
    """"Фильтры"""
    name = models.CharField('Имя', max_length=50, unique=True)
    slug = models.SlugField('url', max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Фильтр'
        verbose_name_plural = 'Фильтры'
        ordering = ["id"]


class DateAdvert(models.Model):
    """"Срок для объявления"""
    name = models.CharField('Имя', max_length=50, unique=True)
    slug = models.SlugField('url', max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Срок'
        verbose_name_plural = 'Сроки'
        ordering = ["id"]



class Advert(models.Model):
    """Объявления"""
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    filters = models.ForeignKey(FilterAdvert, verbose_name='Фильтр', on_delete=models.CASCADE)
    date = models.ForeignKey(DateAdvert, verbose_name='Срок', on_delete=models.CASCADE)
    subject = models.CharField('Тема', max_length=200)
    description = models.TextField('Объявление', max_length=10000)
    images = models.ForeignKey('gallery.Gallery', verbose_name='Изображения', blank=True, null=True, on_delete=models.SET_NULL)
    file = models.FileField('Файл', upload_to='board/', blank=True, null=True)
    price = models.DecimalField('Цена', max_digits=20, decimal_places=2)
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    moderation = models.BooleanField('Модерация', default=False)
    # TODO: для slug генерить путь (user, subject)
    slug = models.SlugField('url', max_length=200, unique=True)
    rating = models.SmallIntegerField("Лайки", default=0)


    def __str__(self):
        return self.subject


    def get_absolute_url(self):
       return reverse('advert-detail', kwargs={'pk': self.pk})

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.description[0:124] + '...'


    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'


class Comment(models.Model):
    commentAdvert = models.ForeignKey(Advert, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField("Объявление", max_length=10000)
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    rating = models.SmallIntegerField("Комментарий", default=0)


    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    user = models.CharField("Пользователь", max_length=100)
    text = models.TextField("Отзыв", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    advert = models.ForeignKey(Advert, verbose_name="Объявление", on_delete=models.CASCADE)

    AGREEMENT = 'AG'
    АCCEPTED = 'AT'
    REJECTED ='RT'
    STATUS_CHOICES = (
        (AGREEMENT, 'Согласование'),
        (АCCEPTED, 'Принято'),
        (REJECTED, 'Отклонено'),
    )
    categoryType = models.CharField(max_length=2, choices=STATUS_CHOICES, default=AGREEMENT)

    def __str__(self):
        return f"{self.user} - {self.advert}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = 'Отзывы'



class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

board/templates/board/advert-detail.html
{% extends 'default.html' %}
{% load custom_filters %}

{% block title %}
Advert
{% endblock title %}
{% block content %}

        <h2>Тема: {{ advert.subject }}</h2>
        <p>Объявление: {{ advert.description }}</p>
        <p>

            {% if advert.file %}
            <p>Изображения: <img src="{{ advert.file.url }}" style="width: 200px;" alt=""></p>
        {% endif %}


        </p>
        <p>Срок: {{ advert.date }}</p>
        <p>Рубрика:{{ advert.filters }}</p>
        <p>Пользователь: {{ advert.user }}</p>
        <p>Цена: {{ advert.price|currency }}</p>
        <p>Дата создания: {{ advert.created }}</p>
        <hr>

<br><br>

                    <div class="row">
                        <div class="single-form-left">
                            <!-- contact form grid -->
                            <div class="contact-single">
                                <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;"></span>Оставить отзыв</h3>
                                <form action="{% url 'add_review' advert.id %}" method="post" class="mt-4">
                                    {%  csrf_token %}
                                    <div class="form-group editContent"
                                         style="outline: none; cursor: inherit;">
                                        <label for="contactcomment" class="editContent"
                                               style="outline: none; cursor: inherit;">Ваш комментарий
                                            *</label>
                                        <textarea class="form-control border" rows="5" name="text"
                                                  id="contactcomment" required=""></textarea>
                                    </div>
                                    <button type="submit"
                                            class="mt-3 btn btn-success btn-block py-3"
                                            style="outline: none; cursor: inherit;">Отправить
                                    </button>
                                </form>
                            </div>
                            <!--  //contact form grid ends here -->
                            </div>
                            {% for review in advert.reviews_set.all %}
                               <div class="media body mt-4">
                                   <h5 class="mt-0 editContent">
                                       {{ review.user }}
                                   </h5>
                                   <p class="mt-2 editContent">
                                       {{ review.text }}
                                   </p>
                                   {% if advert.user == user and review.categoryType == 'AG' %}
                                   <p class="mt-2 editContent">
                                       <a href="{% url 'review_update' review.pk %}">Принять отзыв</a>
                                   </p>
                                   <p class="mt-2 editContent">
                                       <a href="{% url 'review_delete' review.pk %}">Отклонить отзыв</a>
                                   </p>

                                   {% endif %}
                               </div>
                            {% endfor %}

<br><br><br><br>
<div><hr></div>
<br><br>
<div>
    {% if perms.config.change_advert %}
    <a href= "{% url 'advert_update' advert.id %}"><button>Редактировать</button></a>
    {% endif %}
    {% if perms.config.delete_advert %}
    <a href= "{% url 'advert_delete' advert.id %}"><button>Удалить</button></a>
    {% endif %}
</div>

<br><br><br>

{% endblock content %}

board/templates/board/advert-list.html
{% extends 'default.html' %}

{% load custom_filters %}

{% load custom_tags %}


{% block title %}
Adverts
{% endblock title %}

{% block content %}

          <h2>Найти объявление</h2>
    <hr>
    <br>
        {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
           <form action="" method="get">

               {{ filterset.form.as_p }}

               <input type="submit" value="Найти" />
           </form>

 <br>
<hr>

<br>

<h2>Объявления</h2>
<br>
    {% for advert in object_list %}

        <h2><a href="{{ advert.get_absolute_url }}">{{ advert.subject|truncatechars:45 }}</a></h2>
        <p>Рубрика: {{ advert.filters }}</p>
        <p>Цена: {{ advert.price|currency }}</p>
        <p>Дата создания: {{ advert.created }}</p>
        <p>Пользователь: {{ advert.user }}</p>

        <p>
            {% if advert.file %}
            <p>Изображения: <img src="{{ advert.file.url }}" style="width: 60px;" alt=""></p>
            {% endif %}

        </p>

        <hr>


    {% endfor %}



   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}


   {{ page_obj.number }}


   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

    <br>
    <br>
&nbsp;&nbsp;&nbsp;


{% endblock content %}

board/templates/board/advert_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление объявления {{ object.subject }}</h1>
<br>
<hr>
<br><br>
{% if user == advert_user %}
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.subject }}"? </p>
    <input type="submit" value="Да!" />
</form>
{% else %}
<h3>Вы не можете удалить это объявление!</h3>
{% endif %}
{% endblock content %}

board/templates/board/advert_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Изменить объявление {{ object.subject }}</h1>
<hr>
{% if user == advert_user  or is_url_create %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% else %}
<h3>Вы не можете редактировать это объявление!</h3>
{% endif %}
{% endblock content %}