board/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('profile/', include("profiles.urls")),
    path("accounts/", include("allauth.urls")),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path("accounts/", include("accounts.urls")),
    path('', include("config.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/models.py
from django.urls import reverse

from django.contrib.auth.models import User
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.core.cache import cache


class Category(MPTTModel):
    name = models.CharField('Имя', max_length=50, unique=True)
    """Категории объявлений"""
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',
        verbose_name="Родитель"
    )
    slug = models.SlugField('url', max_length=50, unique=True)

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']
        verbose_name = "Категория"




class FilterAdvert(models.Model):
    """"Фильтры"""
    name = models.CharField('Имя', max_length=50, unique=True)
    slug = models.SlugField('url', max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Фильтр'
        verbose_name_plural = 'Фильтры'
        ordering = ["id"]


class DateAdvert(models.Model):
    """"Срок для объявления"""
    name = models.CharField('Имя', max_length=50, unique=True)
    slug = models.SlugField('url', max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Срок'
        verbose_name_plural = 'Сроки'
        ordering = ["id"]



class Advert(models.Model):
    """Объявления"""
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    filters = models.ForeignKey(FilterAdvert, verbose_name='Фильтр', on_delete=models.CASCADE)
    date = models.ForeignKey(DateAdvert, verbose_name='Срок', on_delete=models.CASCADE)
    subject = models.CharField('Тема', max_length=200)
    description = models.TextField('Объявление', max_length=10000)
    images = models.ForeignKey('gallery.Gallery', verbose_name='Изображения', blank=True, null=True, on_delete=models.SET_NULL)
    file = models.FileField('Файл', upload_to='board/', blank=True, null=True)
    price = models.DecimalField('Цена', max_digits=20, decimal_places=2)
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    moderation = models.BooleanField('Модерация', default=False)
    # TODO: для slug генерить путь (user, subject)
    slug = models.SlugField('url', max_length=200, unique=True)
    rating = models.SmallIntegerField("Лайки", default=0)


    def __str__(self):
        return self.subject


    def get_absolute_url(self):
       return reverse('advert-detail', kwargs={'pk': self.pk})

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.description[0:124] + '...'


    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'


class Comment(models.Model):
    commentAdvert = models.ForeignKey(Advert, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField("Объявление", max_length=10000)
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    rating = models.SmallIntegerField("Комментарий", default=0)


    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    user = models.CharField("Пользователь", max_length=100)
    text = models.TextField("Отзыв", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    advert = models.ForeignKey(Advert, verbose_name="Объявление", on_delete=models.CASCADE)

    AGREEMENT = 'AG'
    АCCEPTED = 'AT'
    REJECTED ='RT'
    STATUS_CHOICES = (
        (AGREEMENT, 'Согласование'),
        (АCCEPTED, 'Принято'),
        (REJECTED, 'Отклонено'),
    )
    categoryType = models.CharField(max_length=2, choices=STATUS_CHOICES, default=AGREEMENT)

    def __str__(self):
        return f"{self.user} - {self.advert}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = 'Отзывы'



class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

board/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock content %}

</body>
</html>

board/templates/default.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Bare - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        {% load static %}
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
   <div class="container">
       <a class="navbar-brand" href="http://127.0.0.1:8000/">Доска объявлений</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse"
               data-target="#navbarResponsive"
               aria-controls="navbarResponsive" aria-expanded="false"
               aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarResponsive">
           <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
               <li class="nav-item active">
                   <a class="nav-link" href="http://127.0.0.1:8000/">Главная
<!--                       <span class="sr-only">(current)</span>-->
                   </a>
               </li>
               <li class="nav-item">
                   {% if perms.config.add_advert %}
                   <a class="nav-link" href="http://127.0.0.1:8000/create/">Создать</a>
                   {% endif %}
               </li>

               <li class="nav-item">
                   {% if user.is_authenticated %}
                   <a class="nav-link" href="{% url 'profile-detail' user.id %}">Кабинет</a>
                   {% else %}
                   <a class="nav-link" href="http://127.0.0.1:8000/accounts/login/">Кабинет</a>
                   {% endif %}
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="http://127.0.0.1:8000/subscriptions/">Подписаться</a>
               </li>
               {%  if user.is_authenticated %}
               <li class="nav-item">
                   <a class="nav-link" href="http://127.0.0.1:8000/accounts/logout/">Выйти</a>
               </li>
               {% else %}
               <li class="nav-item">
                   <a class="nav-link" href="http://127.0.0.1:8000/accounts/login/">Войти</a>
               </li>
               {% endif %}
           </ul>
       </div>
   </div>
</nav>

        <!-- Page content-->
        <br>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-left">
                    {% if user.is_authenticated %}
                    <p>Привет {{ user.username }}!</p>
                    {% else %}
                    <p>Авторизируйтесь для создания и редактирования объявлений</p>
                    <a href="http://127.0.0.1:8000/accounts/login/">Войти</a><br><br>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-left">
                    {% block content %}
                    {{ flatpage.content }}
                    {% endblock content %}
                </div>
            </div>
       </div>
    </body>
</html>

board/templates/subscriptions.html
{% extends 'default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}